DROP DATABASE images;
CREATE DATABASE images;

DROP TABLE images;
DROP TABLE keywords;

CREATE TABLE images (
	id SERIAL PRIMARY KEY UNIQUE,
	title VARCHAR(50) NOT NULL,
	img_path TEXT NOT NULL
);

CREATE TABLE keywords (
	id SERIAL PRIMARY KEY UNIQUE,
	title VARCHAR(50) NOT NULL,
	keyword VARCHAR(35) NOT NULL
);